[package]
name = "mcp-rss"
version = "0.1.0"
description = "MCP server that provides RSS tooling."
repository = "https://github.com/haras-unicorn/mcp-rss"
authors = ["haras-unicorn <github@haras-unicorn.net>"]
license-file = "../../LICENSE.md"
readme = "../../README.md"
edition = "2024"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.5.0"
reqwest = { version = "0.12", features = ["json", "gzip"] }
rmcp = { version = "3.1.2", features = ["transport-io"] }
rss = "2"
scraper = "0.23"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
wiremock = "0.6"
